"""Add multi-tenancy and RBAC

Revision ID: 027d7550f8bb
Revises: 21bb5163e7ec
Create Date: 2026-06-29 14:28:47.496096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027d7550f8bb'
down_revision: Union[str, None] = '21bb5163e7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.add_column('asset_relationships', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_asset_relationships_tenant_id'), 'asset_relationships', ['tenant_id'], unique=False)
    op.add_column('assets', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint('uix_asset_type_value', 'assets', type_='unique')
    op.create_unique_constraint('uix_asset_type_value', 'assets', ['tenant_id', 'type', 'value'])
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_constraint('uix_asset_type_value', 'assets', type_='unique')
    op.create_unique_constraint('uix_asset_type_value', 'assets', ['type', 'value'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'tenant_id')
    op.drop_index(op.f('ix_asset_relationships_tenant_id'), table_name='asset_relationships')
    op.drop_column('asset_relationships', 'tenant_id')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
